import { promoAssets } from './assets';
import type { PromoConfig } from './types';

export const coolxPromoConfig: PromoConfig = {
  brandName: 'NOOD',
  username: 'Zion Carter',
  avatarInitials: 'ZC',
  previousGiftAmount: 300,
  todayGiftAmount: 300,
  upgradedGiftAmount: 600,
  currencySymbol: '$',
  creditLabel: 'Excellent!',
  backgroundSymbol: '$',
  devModeEnabled: false,
  autoSpinDurationMs: 5200,
  assets: promoAssets,
  dates: {
    previous: 'Apr 14',
    today: 'Apr 15',
  },
  copy: {
    headlineIntroSmall: 'NOOD Circle is now',
    headlineIntroBig: 'NOOD Deals Hub!',
    floatingHeadline: 'Join the fun and explore all our promotions',
    welcomeLineOne: 'Welcome',
    welcomeLineTwo: 'to NOOD!',
    visitLineOne: "You've visited this event",
    visitLineTwo: '1 time recently',
    previousGiftLabel: 'Your last gift',
    todayGiftLabel: "Today's upgraded gift",
    creditLineOne: 'Your credit on NOOD is',
    creditLineTwo: 'Excellent!',
    creditSpeechBubble: 'Excellent!',
    badgeText: 'For Excellent Credit User',
    upgradeHeadline: 'Congrats!',
    upgradeSubtitle: 'Get $600 reward today!',
    spinHeader: 'Spin for your final reward',
    spinSubheader: 'Take a chance and lock your best NOOD bonus now.',
    spinCtaIdle: 'Spin',
    spinCtaStop: 'Stop',
    spinCtaClaim: 'Claim reward',
  },
  disclaimers: {
    bottomSmallPrint: 'Rewards shown are part of the NOOD Deals Hub promo experience. Offer details can change by account, order status, and market.',
    missedGift: 'Your earlier visit reward expired before it was claimed.',
    todayGift: 'Today’s reward is brighter, bigger, and ready to claim.',
    creditPopup: 'Credit score preview is used only for this promotional experience.',
    upgrade: 'Upgraded rewards are reserved for active NOOD users today.',
    spin: 'Spin result can be controlled from config for QA and live campaigns.',
  },
  timing: {
    introBanner: 1300,
    floatingIcons: 1800,
    welcomeBack: 1400,
    missedGift: 1500,
    todayGift: 1800,
    creditPopup: 1600,
    upgradedGift: 1800,
  },
  wheelSegments: [
    { id: 'p100', label: '$100', value: 100, color: '#ff8d28', textColor: '#241500', weight: 55 },
    { id: 'p200', label: '$200', value: 200, color: '#ffd24d', textColor: '#241500', weight: 10 },
    { id: 'p600', label: '$600 jackpot', value: 600, color: '#ff5f1f', textColor: '#ffffff', badge: 'JACKPOT', weight: 1 },
    { id: 'retry', label: '1 more chance', value: 'Retry', color: '#ffe9a9', textColor: '#241500', weight: 18 },
    { id: 'p150', label: '$150', value: 150, color: '#f5b300', textColor: '#241500', weight: 12 },
    { id: 'p300', label: '$300', value: 300, color: '#ffb347', textColor: '#241500', weight: 4 },
  ],
};
